### ISSUE TITLE
Playing Message twice in rapid succession on Win10 raises RuntimeError

### ISSUE THREAD

**Issue by ethanrich** [pyreiz/pyreiz#10]
``` python
"""
versions
reiz 0.3.5.0
pyglet 1.5
pylsl 1.13.1
pyttsx3 2.81
"""
import time
import reiz
from reiz.audio import Message

canvas = reiz.Canvas()
canvas.open()

msg = Message('ready')
reiz.Cue(canvas, audiostim = msg).show(msg.duration+0.5)
time.sleep(2)
reiz.Cue(canvas, audiostim = msg).show(msg.duration)
```
throws the following error
```python
Exception in thread Thread-34:
Traceback (most recent call last):
  File "C:\Users\Messung\AppData\Local\Continuum\anaconda3\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\Messung\AppData\Local\Continuum\anaconda3\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\tools\pyreiz\reiz\_audio\tts.py", line 68, in play_blocking
    self.engine.runAndWait()
  File "C:\Users\Messung\AppData\Local\Continuum\anaconda3\lib\site-packages\pyttsx3\engine.py", line 177, in runAndWait
    raise RuntimeError('run loop already started')
RuntimeError: run loop already started
'''
```
yet, this snippet works 
``` python
msg.play_blocking()
time.sleep(1)
msg.play()
```

**Comment by agricolab** [comment]
I just tested it on linux with the same dependencies, and it works, so we can pinpoint the bug to how pyttsx3 is interfacing with the Windows Sapi5 TTS-engine.

**Comment by ethanrich** [comment]
Danke, ich werde es machen. 

Ethan

**Comment by agricolab** [comment]
Fixed an related issue, i.e. if no visual was set, the cue would return immediatly, even if duration was set in https://github.com/pyreiz/pyreiz/commit/d8cbd3b238e00aa367e54da8bc1e0e9ac51c9aa2

This explains why 
``` python
msg.play_blocking()
time.sleep(1)
msg.play()
```
worked, because here we actually did block. 


A little bit of tweaking on westside PC returned that delay at  0.21867599 works borderline, i.e. fails sometimes. A relatively safe margin seemed to be at around 0.25
```python
dt = reiz.Cue(canvas, audiostim = msg).show(msg.duration+delay)
dt = reiz.Cue(canvas, audiostim = msg).show(msg.duration)
```

yet, this does not work:
```python
dt = reiz.Cue(canvas, audiostim = msg).show(msg.duration)
time.sleep(1)
dt = reiz.Cue(canvas, audiostim = msg).show(msg.duration)
```

**Comment by agricolab** [comment]
The difference to espeak on linux as  a backend to SAPI5 on Win10 is: With SAPI5, we create the audio on the fly https://github.com/pyreiz/pyreiz/blob/master/reiz/_audio/tts.py#L67 if used with play_blocking, and the same in a thread if run with play https://github.com/pyreiz/pyreiz/blob/master/reiz/_audio/tts.py#L84. With espeak we alwas create a temporary audiofile and load this again https://github.com/pyreiz/pyreiz/blob/master/reiz/_audio/tts.py#L106. 

So it is a threading issue - the engine living in the thread created by `play` (instead of `play_blocking`) has not finished when we already try to speak again. Therefore, this does not work
```python
msg.play()
time.sleep(3)
msg.play()
```

To paraphrase: It is not a bug that Message raises a RunTimeError when we play the next before the last has finished. We actually want this behavior, to prevent mistiming of auditory stimuli. The bug is that Message raises the RunTimeError, although we know the last one has already finished.

**Comment by agricolab** [comment]
As i see it, we have three options.
1. Fix the threading issue, so that ` self.engine.runAndWait` returns reliably within a thread
2. Switch backend on Win10 to espeak, which means we need to install it and it sounds worse.
3. Switch backend on Win10 to [gTTS](https://github.com/pyreiz/pyreiz/blob/master/reiz/_audio/tts.py#L127), which means we need internet access and there is a rate limit
4. Save SAPI5 TTS output to temporary file and load it again, which does for some reason not work with [pyttsx3](https://github.com/nateshmbhat/pyttsx3/blob/master/pyttsx3/drivers/sapi5.py#L65) (see also [this](https://github.com/DeepHorizons/tts/blob/master/tts/sapi.py#L106))
 
Option 4 would be my preferred solution.I tried it during original implementation, but had not time to fix the lack of saving, so i opted for on-the-fly messages.

**Comment by agricolab** [comment]
In the meantime, there was a new release of pyttsx3, but it seems to break the dependencies we have. See https://github.com/pyreiz/pyreiz/issues/12
