### ISSUE TITLE
Error when running reiz-marker

### ISSUE THREAD

**Issue by BettinaTrunk** [pyreiz/pyreiz#11]
When running reiz-marker, I get the following error messages:

OSError: [WinError -2147417850] Der Threadmodus kann nicht nach dem Einstellen geändert werden

TypeError: category must be a Warning subclass, not 'str'

**Comment by moan0s** [comment]
The error occurs for `reiz-marker` and `reiz-marker -h `

**Comment by agricolab** [comment]
Sounds like a Win10 Update wreaked havoc

**Comment by agricolab** [comment]
Can you also post the traceback, and your version on Python, Windows and reiz?

**Comment by BettinaTrunk** [comment]
Sure:
- Traceback:
\\\
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\AGNPT-M-001\Anaconda3\lib\site-packages\pyglet\media\__init__.py", line 143, in <module>
    add_default_media_codecs()
  File "C:\Users\AGNPT-M-001\Anaconda3\lib\site-packages\pyglet\media\codecs\__init__.py", line 175, in add_default_media_codecs
    add_decoders(wmf)
  File "C:\Users\AGNPT-M-001\Anaconda3\lib\site-packages\pyglet\media\codecs\__init__.py", line 128, in add_decoders
    for decoder in module.get_decoders():
  File "C:\Users\AGNPT-M-001\Anaconda3\lib\site-packages\pyglet\media\codecs\wmf.py", line 890, in get_decoders
    return [WMFDecoder()]
  File "C:\Users\AGNPT-M-001\Anaconda3\lib\site-packages\pyglet\media\codecs\wmf.py", line 836, in __init__
    warnings.warn('WMF failed to initialize threading:', err.strerror)
TypeError: category must be a Warning subclass, not 'str'
\\\

- Python Version: 3.7

- Windows Version: 10.0.17134

- Reiz: pyglet-1.5.5

**Comment by agricolab** [comment]
The traceback clearly shows that this is a an error within pyglet. Apparently they were working a lot on the WMF backend (see [here](https://github.com/pyglet/pyglet/releases)). Try `pip install pyglet==1.5.0` to rewind to an older version of pyglet and run `reiz-marker` afterwards again. If the error persists, you can also try older versions of pyglet, or install the most recent development branch from github.

**Comment by agricolab** [comment]
See also https://github.com/pyglet/pyglet/issues/174 and the partial fix with https://github.com/pyglet/pyglet/pull/183

**Comment by agricolab** [comment]
Can i get an update whether this error still persists?

**Comment by BettinaTrunk** [comment]
Going back to pyglet 1.5.0 as you suggested solved the error!
