### ISSUE TITLE
Text to speech backend not found on Windows during import of reiz

### ISSUE THREAD

**Issue by moan0s** [pyreiz/pyreiz#14]
With Reiz 3.5.1 the following OS Error is thrown while importing reiz.

```
(studypowerphase) C:\Users\study-power-phase\Desktop\study_power_phase_tms\power_and_phase_tms>python protocol.py
Traceback (most recent call last):
  File "C:\Users\study-power-phase\anaconda3\envs\studypowerphase\lib\site-packages\pyttsx3\__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "C:\Users\study-power-phase\anaconda3\envs\studypowerphase\lib\weakref.py", line 137, in __getitem__
    o = self.data[key]()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\study-power-phase\Desktop\study_power_phase_tms\power_and_phase_tms\protocol.py", line 8, in <module>
    import reiz
  File "C:\Users\study-power-phase\anaconda3\envs\studypowerphase\lib\site-packages\reiz\__init__.py", line 8, in <module>
    import reiz.audio as audio
  File "C:\Users\study-power-phase\anaconda3\envs\studypowerphase\lib\site-packages\reiz\audio.py", line 76, in <module>
    library = make_library()
  File "C:\Users\study-power-phase\anaconda3\envs\studypowerphase\lib\site-packages\reiz\audio.py", line 44, in make_library
    lib[name] = Message(**args)
  File "C:\Users\study-power-phase\anaconda3\envs\studypowerphase\lib\site-packages\reiz\_audio\tts.py", line 35, in __init__
    self.engine = pyttsx3.init()
  File "C:\Users\study-power-phase\anaconda3\envs\studypowerphase\lib\site-packages\pyttsx3\__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "C:\Users\study-power-phase\anaconda3\envs\studypowerphase\lib\site-packages\pyttsx3\engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "C:\Users\study-power-phase\anaconda3\envs\studypowerphase\lib\site-packages\pyttsx3\driver.py", line 50, in __init__
    self._module = importlib.import_module(name)
  File "C:\Users\study-power-phase\anaconda3\envs\studypowerphase\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\study-power-phase\anaconda3\envs\studypowerphase\lib\site-packages\pyttsx3\drivers\sapi5.py", line 1, in <module>
    import comtypes.client  # Importing comtypes.client will make the gen subpackage
  File "C:\Users\study-power-phase\anaconda3\envs\studypowerphase\lib\site-packages\comtypes\__init__.py", line 160, in <module>
    CoInitializeEx()
  File "C:\Users\study-power-phase\anaconda3\envs\studypowerphase\lib\site-packages\comtypes\__init__.py", line 151, in CoInitializeEx
    _ole32.CoInitializeEx(None, flags)
  File "_ctypes/callproc.c", line 997, in GetResult
OSError: [WinError -2147417850] Der Threadmodus kann nicht nach dem Einstellen geändert werden
```

**Comment by agricolab** [comment]
> :\Users\study-power-phase\anaconda3\envs\studypowerphase\lib\site-packages\pyttsx3\__init__.py", line 20, in init
    eng = _activeEngines[driverName]
    
 says it's an error inherited from ttsx, i.e. the text to speech engine, looks as if the engine is missing.

**Comment by agricolab** [comment]
try `pip install -U pyttsx3`

**Comment by agricolab** [comment]
If that doesn't work, check whether your Windows has a Text-to-Speech engine installed at all? Or deinstall pyttsx3, iirc then reiz creates silence instead of messages...

**Comment by moan0s** [comment]
Installing (or uninstalling) pyttsx3 does not help. This small example runs without problems
```
import pyttsx3
engine = pyttsx3.init()
engine.say("I will speak this text")
engine.runAndWait()
```

**Comment by agricolab** [comment]
This stems from a conflict between pyglet.media and pyttsx3 in setting thread modes, which can apparently only be set once.

```
import pyttsx3
engine = pyttsx3.init()
import pyglet.media
```
raises a warning:
> pyglet\media\codecs\wmf.py:838: UserWarning: [WinError -2147417850] Cannot change thread mode after it is set
  warnings.warn(str(err))

```
import pyglet.media
import pyttsx3
engine = pyttsx3.init()
```
throws an exception
> OSError: [WinError -2147417850] Cannot change thread mode after it is set

**Comment by agricolab** [comment]
Fix requires pyttsx3 to support file saving, which was implemented at least in 2.9 and/or 5d3755b060a980f48fcaf81df018dd06cbd17a8f

**Comment by agricolab** [comment]
Use now the idiom ```import reiz.api as reiz``` to have same usage as before.
Changed this, to ease debugging and prevent breaking during imports via __init__

**Comment by agricolab** [comment]
The `fix` is based on changing the order of imports, we now import pyttsx3 first, then pyglet, because that only throws a warning, not an exception. That means, tread with caution, buts might pop up somewhere else during audio playing. If that happens, i'll completely outsource TTS from Reiz, so the user has to create speech audioclips independently, or i'll try JIT-TTS-compilation a separate process.

https://github.com/neuromti/study_power_phase_tms/commit/af96d885a47414b2d9a6ced46ffa8f2983fd088e would now be superflous?

Tagging @mkeute because @moan0s is on extended shoreleave.
